// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/2/2024, 10:34:35 AM
const configMerger = require("/Users/bartoszciesla/git/linear-card-nuxt/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.4_rollup@4.19.1/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/bartoszciesla/git/linear-card-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/plugins/**/*.{js,ts,mjs}","/Users/bartoszciesla/git/linear-card-nuxt/composables/**/*.{js,ts,mjs}","/Users/bartoszciesla/git/linear-card-nuxt/utils/**/*.{js,ts,mjs}","/Users/bartoszciesla/git/linear-card-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bartoszciesla/git/linear-card-nuxt/app.config.{js,ts,mjs}"] }));

module.exports = config
